name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 23:30 hours
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: JeanneDuPre/github-profile-summary-cards@v3
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
